version: '3.8'
services:
  new-project:
    image: ghcr.io/CasPro48/new-project:latest
    restart: unless-stopped
    environment:
      - PORT=5002
    ports:
      - "5002:5002"
    volumes:
      - ./data:/app/data:rw
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5002/ || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
