global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'nexus-api-gateway'
    static_configs:
      - targets: ['host.docker.internal:4000']
    metrics_path: '/metrics'

  - job_name: 'nexus-postgres'
    static_configs:
      - targets: ['nexus_db:5432']

  - job_name: 'nexus-redis'
    static_configs:
      - targets: ['nexus_cache:6379']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
